[project]
name = "scripts"
version = "0.1.0"
description = "Data management scripts for Thomas Bernhard in Translation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "acdh-baserow-pyutils>=0.10",
    "python-dotenv>=1.0.1",
    "typesense>=0.21.0",
]
